name: Run Python Scripts Based on Datetime
on:
  schedule:
    # Executar no primeiro dia de cada mês às 00:00 UTC
    - cron: '0 0 1 * *'  # A cron expression para rodar mensalmente no primeiro dia do mês
  
  workflow_dispatch:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: works
  
jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          
      - name: Installing package list and necessary packages
        run: |
          apt list --installed
          sudo apt purge google-chrome-stable
          sudo apt-get install xvfb
          python -m pip install --upgrade pip
          pip install -r Scripts/Daniel/requirements.txt
          python -m pip install --upgrade pip
          pip install -r Scripts/Daniel/requirements.txt
          
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Executar Script
        run: python Scripts/Daniel/run_scripts.py
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Atualização agendada das bases de dados"
      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Atualização agendada das bases de dados"
            git push
          fi
